apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-airflow-dags
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/airflow/dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 50Mi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-airflow-logs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/airflow/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual